// Public URLs are deliberately stable for media loading and deployment.
export const images = {
  "emsLogo": "/ems-logo.png",
  "egypt": "/flags/egypt.svg",
  "saudiArabia": "/flags/saudi-arabia.svg",
  "siemens": "/siemens.png",
  "cisco": "/cisco.png",
  "python": "/python.svg",
  "visualStudio": "/visual-studio.webp",
  "aws": "/aws.svg",
  "oracle": "/oracle.png",
  "cPU1510": "/store-products/CPU 1510.jpg",
  "cPU1516": "/store-products/CPU 1516.jpg",
  "eT200SPIM": "/store-products/ET 200SP [IM].jpg",
  "cM1500": "/store-products/CM 1500.jpg",
  "dO1500": "/store-products/DO 1500.jpg",
  "dI1500": "/store-products/DI 1500.jpg",
  "aI1500": "/store-products/AI 1500.jpg",
  "aO1500": "/store-products/AO 1500.jpg",
  "baseUnitA0White": "/store-products/BaseUnit [A0 White].jpg",
  "baseUnitA0Black": "/store-products/BaseUnit [A0 Black].jpg",
  "baseUnitA1White": "/store-products/BaseUnit [A1 White].jpg",
  "baseUnitA1Black": "/store-products/BaseUnit [A1 Black].jpg",
  "cPU1200": "/store-products/CPU 1200.jpg",
  "cM1200": "/store-products/CM 1200.jpg",
  "dIO1200": "/store-products/DI-O 1200.jpg",
  "dI1200": "/store-products/DI 1200.jpg",
  "dO1200": "/store-products/DO 1200.jpg",
  "aO1200": "/store-products/AO 1200.jpg",
  "aI1200": "/store-products/AI 1200.jpg",
  "hMI": "/store-products/HMI.jpg",
  "pS10A": "/store-products/PS [10 A].jpg",
  "memoryCard256MB": "/store-products/Memory Card 256MB.jpg",
  "memoryCard12MB6ES79548LE040AA0": "/store-products/Memory Card 12MB - 6ES7954-8LE04-0AA0.jpg",
  "memoryCard12MB6ES79548LE030AA0": "/store-products/Memory Card 12MB - 6ES7954-8LE03-0AA0.jpg",
  "busAdapter1500": "/store-products/BusAdapter 1500.jpg",
  "pressureTransmitter7MF15653CB001AA1": "/store-products/Pressure Transmitter - 7MF1565-3CB00-1AA1.jpg",
  "levelTransmitter": "/store-products/Level Transmitter.jpg",
  "cPU1200G21214": "/store-products/CPU 1200 G2 1214.png",
  "cPU1200G21212": "/store-products/CPU 1200 G2 1212.png",
  "assetDI1200G2SM": "/store-products/16 DI 1200 G2 SM.png",
  "assetDI1200G2SB": "/store-products/8 DI 1200 G2 SB.jpg",
  "assetDO1200G2SM": "/store-products/16 DO 1200 G2 SM.png",
  "assetAI1200G2SM": "/store-products/8 AI 1200 G2 SM.png",
  "assetAI1200G2SB": "/store-products/4 AI 1200 G2 SB.png",
  "assetAO1200G2SB": "/store-products/4 AO 1200 G2 SB.png",
  "cMBOARD1200G2": "/store-products/CM BOARD 1200 G2.png",
  "ultrasonicFlowmeterFST020": "/store-products/Ultrasonic flowmeter FST020.png",
  "pressureTransmitter7MF15653CB005EA1": "/store-products/Pressure Transmitter - 7MF1565-3CB00-5EA1.jpg",
  "dataCenter": "/data-center.mp4",
  "ziaSmartBuildingDashboard": "/zia-smart-building-dashboard.mp4",
  "smartWaterStationDashboard": "/smart-water-station-dashboard.mp4",
  "smartHospitalMonitoring": "/smart-hospital-monitoring.mp4",
  "industrialScadaMonitoring": "/industrial-scada-monitoring.mp4",
  "alAttalNewCapital": "/al-attal-new-capital.mp4",
  "wadiZahaSmartResidential": "/wadi-zaha-smart-residential.mp4",
  "ahmedElzayat": "/ahmed-elzayat.jpeg",
  "cBC20TALK": "/CBC%20TALK.mp4",
  "alNamaHero": "/al-nama-hero.mp4",
  "heroControlRoom04": "/hero-control-room-04.jpg",
  "geminiGeneratedImage1ujzed1ujzed1ujz": "/Gemini_Generated_Image_1ujzed1ujzed1ujz.jpg",
  "investorsWater": "/investors-water.mp4",
  "industryWaterDashboard": "/industry-water-dashboard.png",
  "parkLaneCompounds": "/park-lane-compounds.mp4",
  "industryMallsDashboard": "/industry-malls-dashboard.png",
  "cn05Buildings": "/cn-05-buildings.mp4",
  "industryTowersDashboard": "/industry-towers-dashboard.png",
  "abdellatefIndustrial": "/abdellatef-industrial.mp4",
  "industrialAbdellatefPoster": "/industrial-abdellatef-poster.png",
  "sectorTowersCn05": "/sector-towers-cn05.png",
  "homeServiceBms": "/ChatGPT Image Sep 28, 2026, 05_15_51 PM.png",
  "serviceScadaControlRoom": "/service-scada-control-room.png",
  "serviceIot": "/service-iot.png",
  "serviceAi": "/service-ai.png",
  "screenshot20260914221026": "/Screenshot 2026-09-14 221026.png",
  "serviceDigitalTwinDashboard": "/service-digital-twin-dashboard.jpg",
  "suezMedicalComplex": "/suez-medical-complex.jpg",
  "abdellatifJameelFactory": "/abdellatif-jameel-factory.jpg",
  "heroControlRoom02": "/hero-control-room-02.jpg",
  "heroControlRoom03": "/hero-control-room-03.jpg",
  "heroControlRoom05": "/hero-control-room-05.jpg",
  "sectorCompoundsParkLane": "/sector-compounds-park-lane.png",
  "sectorHospitalsSuez": "/sector-hospitals-suez.png",
  "industryHospitalsDashboard": "/industry-hospitals-dashboard.png",
  "sectorFactoriesAbdellatif": "/sector-factories-abdellatif.png",
  "sectorWaterInvestors": "/sector-water-investors.png",
  "dataCenter1": "/data-center-1.jpg",
  "heroData3": "/hero-data-3.jpg"
} as const
