import { Link, Navigate, useParams } from 'react-router-dom'
import { motion, useReducedMotion } from 'framer-motion'
import { HiOutlineArrowLeft, HiOutlineArrowRight, HiOutlineCheck, HiOutlineCpuChip } from 'react-icons/hi2'
import { getProjectById, projects } from '../data/projects'

const ease = [0.22, 1, 0.36, 1]

function Reveal({ children, className = '', delay = 0 }) {
  const reducedMotion = useReducedMotion()
  return <motion.div initial={reducedMotion ? false : { opacity: 0, y: 28 }} whileInView={reducedMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true, margin: '-70px' }} transition={{ duration: .7, delay, ease }} className={className}>{children}</motion.div>
}

function Architecture({ project }) {
  const reducedMotion = useReducedMotion()
  const nodes = ['Field systems', project.services[0], project.services[1] || 'Control layer', 'ZETA platform', 'Operators & insight']
  return <div className="relative mt-12 rounded-[1.4rem] border border-white/10 bg-[#07182e]/85 p-5 shadow-[0_24px_80px_rgba(0,0,0,.25)] sm:p-8 lg:p-12">
    <div className="grid-bg absolute inset-0 rounded-[inherit] opacity-25" />
    <div className="relative grid gap-3 lg:grid-cols-5 lg:gap-0">{nodes.map((node, index) => <div key={node} className="relative flex items-center lg:block">
      <motion.div initial={reducedMotion ? false : { opacity: .25, scale: .92 }} whileInView={reducedMotion ? undefined : { opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ delay: index * .14, duration: .5 }} className="group relative z-10 flex min-h-24 flex-1 items-center justify-center rounded-xl border border-[#299BF0]/35 bg-[#091f3b] px-4 text-center shadow-[0_0_0_rgba(35,199,255,0)] transition duration-300 hover:border-cyan-300 hover:shadow-[0_0_30px_rgba(35,199,255,.14)]"><span><b className="mb-2 block font-mono text-[9px] font-normal tracking-[.2em] text-cyan-300">L{index + 1}</b><span className="text-xs font-semibold text-slate-200">{node}</span></span></motion.div>
      {index < nodes.length - 1 && <div className="relative flex h-9 w-8 flex-none items-center justify-center lg:h-24 lg:w-full"><span className="h-full w-px bg-white/10 lg:h-px lg:w-full" /><motion.span initial={reducedMotion ? false : { scaleY: 0 }} whileInView={reducedMotion ? undefined : { scaleY: 1 }} viewport={{ once: true }} transition={{ duration: .65, delay: .3 + index * .14 }} className="absolute h-full w-px origin-top bg-gradient-to-b from-cyan-300 to-[#299BF0] lg:h-px lg:w-full lg:origin-left lg:bg-gradient-to-r" /><span className="absolute h-2 w-2 rounded-full bg-cyan-200 shadow-[0_0_14px_#23C7FF]" /></div>}
    </div>)}</div>
  </div>
}

export default function ProjectDetails() {
  const { id } = useParams()
  const project = getProjectById(id)
  const reducedMotion = useReducedMotion()
  if (!project) return <Navigate to="/case-studies" replace />
  const index = projects.findIndex(item => item.id === project.id)
  const next = projects[(index + 1) % projects.length]

  return <main className="project-detail-page overflow-hidden bg-[#010B1F] text-white">
    <section className="relative min-h-[680px] overflow-hidden pt-24 lg:min-h-[82vh]">
      {project.videoSrc ? <video src={project.videoSrc} poster={project.image} autoPlay muted loop playsInline className="absolute inset-0 h-full w-full object-cover" /> : <img src={project.image} alt={`${project.name} project`} className="absolute inset-0 h-full w-full object-cover" />}
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(1,11,31,.98)_0%,rgba(1,11,31,.78)_55%,rgba(1,11,31,.24)_100%)]" /><div className="absolute inset-0 bg-gradient-to-t from-[#010B1F] via-transparent to-[#010B1F]/50" /><div className="grid-bg absolute inset-0 opacity-15" />
      <div className="container-ems relative flex min-h-[590px] items-end pb-[clamp(4rem,8vw,7rem)]"><motion.div initial={reducedMotion ? false : { opacity: 0, y: 28 }} animate={reducedMotion ? undefined : { opacity: 1, y: 0 }} transition={{ duration: .85, ease }} className="max-w-4xl"><Link to="/case-studies" className="inline-flex items-center gap-2 text-xs text-slate-300 transition hover:gap-3 hover:text-cyan-200"><HiOutlineArrowLeft /> Case studies</Link><p className="eyebrow mt-8">Project {String(index + 1).padStart(2, '0')} / {project.industry}</p><h1 className="type-page-title mt-5 font-serif tracking-[-.03em]">{project.name}</h1><p className="type-lead mt-6 max-w-2xl text-slate-300">{project.description}</p><div className="mt-7 flex flex-wrap gap-2">{project.services.map(service => <span key={service} className="rounded-full border border-white/15 bg-[#010B1F]/55 px-3 py-1.5 text-[10px] text-slate-200 backdrop-blur">{service}</span>)}</div></motion.div></div>
    </section>

    <section className="section-padding"><div className="container-ems grid gap-10 lg:grid-cols-[.75fr_1.25fr]"><Reveal><p className="eyebrow">01 / The challenge</p><h2 className="type-section-title mt-4 font-serif">The operating context.</h2></Reveal><Reveal delay={.08}><p className="type-lead text-slate-300">{project.challenge}</p><div className="mt-8 border-l border-cyan-300/40 pl-5"><p className="type-body text-slate-400">The project required coordinated visibility across its engineering systems, with information structured so operational teams could understand conditions and respond with confidence.</p></div></Reveal></div></section>

    <section className="section-padding border-y border-white/10 bg-[#061326]"><div className="container-ems grid gap-10 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><Reveal><p className="eyebrow">02 / The solution</p><h2 className="type-section-title mt-4 font-serif">Engineering and intelligence, connected.</h2><p className="type-lead mt-6 text-slate-300">{project.solution}</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{project.technologies.map(item => <div key={item} className="flex items-center gap-3 rounded-xl border border-white/10 bg-white/[.035] p-4 text-sm text-slate-300 transition hover:border-cyan-300/35 hover:bg-cyan-300/[.04]"><HiOutlineCheck className="flex-none text-cyan-300" />{item}</div>)}</div></Reveal><Reveal delay={.1} className="relative min-h-[380px] overflow-hidden rounded-[1.4rem] border border-white/10"><img src={project.image} alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#010B1F]/90 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 right-6"><p className="font-mono text-[9px] uppercase tracking-[.2em] text-cyan-300">Integrated operating view</p><p className="mt-2 font-serif text-2xl">{project.location}</p></div></Reveal></div></section>

    <section className="section-padding"><div className="container-ems"><Reveal className="max-w-3xl"><p className="eyebrow">03 / System architecture</p><h2 className="type-section-title mt-4 font-serif">From field signal to operational decision.</h2><p className="type-body mt-5 text-slate-400">Each layer has a clear role. Together they create the connected operating context demonstrated in this project.</p></Reveal><Architecture project={project} /></div></section>

    <section className="section-padding border-y border-white/10 bg-[#061326]"><div className="container-ems grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><Reveal><HiOutlineCpuChip className="h-8 w-8 text-cyan-300" /><p className="eyebrow mt-6">04 / Technology</p><h2 className="type-section-title mt-4 font-serif">A focused technical stack.</h2></Reveal><div className="grid grid-cols-2 border-l border-t border-white/10 sm:grid-cols-3">{[...project.services, ...project.technologies].slice(0, 9).map((tech, i) => <motion.div key={tech} initial={reducedMotion ? false : { opacity: 0 }} whileInView={reducedMotion ? undefined : { opacity: 1 }} viewport={{ once: true }} transition={{ delay: i * .05 }} className="flex min-h-28 items-end border-b border-r border-white/10 p-4 text-xs font-semibold text-slate-300 transition hover:bg-cyan-300/[.05] hover:text-cyan-100"><span><b className="mb-2 block font-mono text-[9px] font-normal text-cyan-300/70">T{String(i + 1).padStart(2, '0')}</b>{tech}</span></motion.div>)}</div></div></section>

    <section className="section-padding"><div className="container-ems"><Reveal className="max-w-3xl"><p className="eyebrow">05 / Results</p><h2 className="type-section-title mt-4 font-serif">Operational outcomes, made visible.</h2></Reveal><div className="mt-10 grid gap-px overflow-hidden rounded-[1.4rem] border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-4">{project.results.map((result, i) => <motion.div key={result.label} initial={reducedMotion ? false : { opacity: 0, y: 16 }} whileInView={reducedMotion ? undefined : { opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * .07 }} className="bg-[#07182e] p-6 lg:p-8"><p className="font-serif text-[clamp(1.8rem,3vw,3rem)] text-cyan-100">{result.value}</p><p className="mt-3 text-[10px] uppercase tracking-[.16em] text-slate-400">{result.label}</p></motion.div>)}</div></div></section>

    <section className="section-padding border-y border-white/10 bg-[#061326]"><div className="container-ems"><Reveal><p className="eyebrow">06 / Project gallery</p><h2 className="type-section-title mt-4 font-serif">Engineering in its operating environment.</h2></Reveal><div className="mt-10 grid auto-rows-[220px] gap-4 sm:grid-cols-2 lg:grid-cols-12 lg:auto-rows-[260px]"><div className="group relative overflow-hidden rounded-[1.2rem] sm:row-span-2 lg:col-span-7"><img src={project.image} alt={`${project.name} overview`} className="h-full w-full object-cover transition duration-1000 group-hover:scale-105" /></div><div className="group relative overflow-hidden rounded-[1.2rem] lg:col-span-5">{project.videoSrc ? <video src={project.videoSrc} poster={project.image} autoPlay muted loop playsInline className="h-full w-full object-cover" /> : <img src="/hero-control-room-02.jpg" alt="EMS control environment" className="h-full w-full object-cover transition duration-1000 group-hover:scale-105" />}</div><div className="group relative overflow-hidden rounded-[1.2rem] lg:col-span-5"><img src="/hero-control-room-04.jpg" alt="Connected operations visualization" className="h-full w-full object-cover transition duration-1000 group-hover:scale-105" /></div></div></div></section>

    <section className="relative min-h-[480px] overflow-hidden"><img src={next.image} alt="" className="absolute inset-0 h-full w-full object-cover opacity-45 transition duration-1000" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(1,11,31,.98),rgba(1,11,31,.55))]" /><div className="container-ems relative flex min-h-[480px] items-center"><div><p className="eyebrow">Next case study</p><h2 className="type-section-title mt-5 max-w-3xl font-serif">{next.name}</h2><p className="type-body mt-4 max-w-xl text-slate-300">{next.description}</p><Link to={`/case-studies/${next.id}`} className="btn-primary mt-7">Continue exploring <HiOutlineArrowRight /></Link></div></div></section>
  </main>
}
