import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { HiOutlineArrowRight, HiOutlineCheck, HiOutlineCubeTransparent } from 'react-icons/hi2'
import { benefits, deploymentModels, platformLayers } from '../data/zeta'

export default function Solutions() {
  return <main className="overflow-hidden bg-[#010B1F] text-white">
    <section className="relative min-h-[680px] overflow-hidden pt-28"><div className="absolute inset-0 grid-bg opacity-35" /><div className="absolute left-1/2 top-1/2 h-[min(70vw,680px)] w-[min(70vw,680px)] -translate-x-1/2 -translate-y-1/2 rounded-full border border-cyan-300/15 bg-cyan-300/[.025] shadow-[0_0_160px_rgba(0,102,255,.2)]" /><div className="container-ems relative grid min-h-[560px] items-center gap-12 py-16 lg:grid-cols-[1fr_.9fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }}><p className="eyebrow">ZETA Platform</p><h1 className="mt-5 max-w-3xl font-serif text-[clamp(2.5rem,5.5vw,5rem)] leading-[1.02]">The digital operating layer for connected facilities.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-slate-300">ZETA integrates building management, SCADA, IoT, AI, digital environments and robotics so teams can see and understand complex operations in context.</p><Link to="/contact" className="btn-primary mt-8">Discuss ZETA <HiOutlineArrowRight /></Link></motion.div><div className="relative mx-auto aspect-square w-full max-w-[480px]"><div className="absolute inset-[12%] animate-[spin_32s_linear_infinite] rounded-full border border-dashed border-cyan-300/25" /><div className="absolute inset-[24%] animate-[spin_22s_linear_infinite_reverse] rounded-full border border-white/10" /><div className="absolute inset-[34%] flex items-center justify-center rounded-full border border-cyan-300/35 bg-[#07182e] shadow-[0_0_80px_rgba(0,200,255,.15)]"><HiOutlineCubeTransparent className="h-14 w-14 text-cyan-200" /></div>{platformLayers.map((layer, index) => { const Icon = layer.icon; const angle = (index / platformLayers.length) * Math.PI * 2; const x = 50 + Math.cos(angle) * 42; const y = 50 + Math.sin(angle) * 42; return <div key={layer.id} style={{ left: `${x}%`, top: `${y}%` }} className="absolute flex h-14 w-14 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-xl border border-white/15 bg-[#0b2542]/95 shadow-xl backdrop-blur"><Icon className="h-5 w-5 text-cyan-300" /></div>})}</div></div></section>

    <section className="section-padding border-y border-white/10 bg-[#071629]"><div className="container-ems"><div className="max-w-2xl"><p className="eyebrow">Platform architecture</p><h2 className="mt-4 font-serif text-[clamp(2rem,4vw,3rem)]">Six layers. One operational picture.</h2></div><div className="mt-11 grid grid-cols-[repeat(auto-fit,minmax(min(100%,310px),1fr))] gap-5">{platformLayers.map((layer, index) => { const Icon = layer.icon; return <motion.article key={layer.id} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: (index % 3) * .06 }} className="rounded-xl border border-white/10 bg-[#07182e] p-[clamp(1.3rem,3vw,2rem)]"><div className="flex items-center justify-between"><Icon className="h-6 w-6 text-cyan-300" /><span className="font-mono text-[10px] text-slate-600">{layer.label}</span></div><h3 className="mt-6 text-lg font-semibold">{layer.title}</h3><p className="mt-3 text-[13px] leading-6 text-slate-400">{layer.description}</p><div className="mt-5 space-y-2">{layer.capabilities.map(item => <p key={item} className="flex items-center gap-2 text-xs text-slate-300"><HiOutlineCheck className="flex-none text-cyan-300" />{item}</p>)}</div></motion.article>})}</div></div></section>

    <section id="digital-twin" className="section-padding"><div className="container-ems grid gap-10 lg:grid-cols-2 lg:items-center"><div className="relative aspect-[4/3] overflow-hidden rounded-xl border border-white/10"><img src="https://images.unsplash.com/photo-1480714378408-67cf0d13bc1b?auto=format&fit=crop&w=1600&q=82" alt="Digital city environment" loading="lazy" className="h-full w-full object-cover opacity-55" /><div className="absolute inset-0 grid-bg opacity-30" /><div className="absolute inset-0 bg-gradient-to-t from-[#030a13] to-transparent" /><div className="absolute bottom-6 left-6 right-6 grid grid-cols-3 gap-2">{['Live devices', '3D context', 'Remote insight'].map(item => <span key={item} className="rounded border border-white/15 bg-[#061326]/70 px-3 py-3 text-center text-[10px] backdrop-blur">{item}</span>)}</div></div><div><p className="eyebrow">Digital Twin</p><h2 className="mt-4 font-serif text-[clamp(2rem,4vw,3rem)]">Physical systems, understood in digital context.</h2><p className="mt-5 text-sm leading-7 text-slate-400">ZETA connects a 3D environment to real devices, giving operations and maintenance teams a remote way to explore systems, understand relationships and simulate conditions.</p><ul className="mt-7 space-y-3">{['Navigate electromechanical systems spatially', 'Bring live equipment data into a visual model', 'Support remote operations and maintenance understanding', 'Use simulation to improve operational readiness'].map(item => <li key={item} className="flex gap-3 text-sm text-slate-300"><HiOutlineCheck className="mt-0.5 flex-none text-cyan-300" />{item}</li>)}</ul></div></div></section>

    <section className="section-padding bg-[#071629]"><div className="container-ems grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Flexible deployment</p><h2 className="mt-4 font-serif text-[clamp(2rem,4vw,3rem)]">A route from control systems to connected intelligence.</h2><p className="mt-4 text-sm leading-7 text-slate-400">The platform connects BMS and SCADA with IoT and AI through deployment models suited to different operational environments.</p></div><div className="grid gap-4 sm:grid-cols-3">{deploymentModels.map(({ icon: Icon, title, text }) => <article key={title} className="rounded-xl border border-white/10 bg-white/[.035] p-6"><Icon className="h-6 w-6 text-cyan-300" /><h3 className="mt-6 text-sm font-semibold">{title}</h3><p className="mt-2 text-[13px] leading-6 text-slate-400">{text}</p></article>)}</div></div></section>

    <section className="section-padding"><div className="container-ems"><p className="eyebrow">Platform value</p><h2 className="mt-4 max-w-2xl font-serif text-[clamp(2rem,4vw,3rem)]">Built to improve the way facilities perform.</h2><div className="mt-10 grid grid-cols-[repeat(auto-fit,minmax(min(100%,260px),1fr))] gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10">{benefits.map(([title, text]) => <article key={title} className="bg-[#07182e] p-6"><h3 className="text-sm font-semibold text-cyan-100">{title}</h3><p className="mt-2 text-[13px] leading-6 text-slate-400">{text}</p></article>)}</div><div className="mt-12 text-center"><Link to="/contact" className="btn-primary">Explore a ZETA deployment <HiOutlineArrowRight /></Link></div></div></section>
  </main>
}
